inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AllCops:
  Exclude:
      - 'app/views/reports/**/*'
      - 'app/views/report_requests/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false 

Style/ColonMethodCall:
  Enabled: false 

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  EnforcedStyle: brackets

Style/AndOr:
  EnforcedStyle: conditionals

Style/FrozenStringLiteralComment:
  Enabled: false  

Style/RedundantReturn:
  AllowMultipleReturnValues: true

GitHub/RailsControllerRenderPathsExist:
  Enabled: false

GitHub/RailsControllerRenderActionSymbol:
  Enabled: false
